### ISSUE TITLE
Really awesome 

### ISSUE THREAD

**Issue by hatonthecat** [evansm7/pico-mac#1]
Very cool project! I was curious if you'd be interested in a solar powered mac (with tcp/ip) 

https://www.sparkfun.com/products/15443 384K of RAM

with a TCP/IP stack? https://macgui.com/news/article.php?t=492#:~:text=Would%20you%20believe%20that%20there,the%20Mac%20512K%20was%20released.

could power the display https://www.sharpsde.com/technologies-for/memory-in-pixels/miptechnology/

**Comment by evansm7** [comment]
Ha nice! Too expensive and feature-creep, but thanks for the suggestions :) Yes indeed faster MCUs with more memory are available, but then the Pico was the challenge.
