### ISSUE TITLE
PicoMac UF2 image creator broken?

### ISSUE THREAD

**Issue by fvillanustre** [evansm7/pico-mac#10]
Ron, it seems that the service on the website for the PicoMac UF2 image creation is not executing correctly (it just hangs waiting for the image to be ready). I don't see any links to provide feedback there, so I hope this works (even though it's truly not a bug).

Thanks,

Flavio

**Comment by RonsCompVids** [comment]
If you try it now, does it work?  Also, does your disk image conform to what the site is looking for?

**Comment by evansm7** [comment]
Can't repro?
