### ISSUE TITLE
SD Card disk image

### ISSUE THREAD

**Issue by horsiezoo** [evansm7/pico-mac#13]
Hi there, fantastic project! The first build is great, I deleted my ./pico-mac dir and started again this morning after I saw your update.
I'm having trouble understanding :
 "...copy your disc image into one of the following files in the root of the card:

umac0.img: A normal read/write disc image"

Do you mean create an empty .img say 10MB on FAT16 ? format SD card named umac0.img and then copy a known good mac boot disk image into that?

Or: rename a known good boot image to umac0.img on SD card ? 
(I've tried both)

Else if the above is correct, its my SD card wiring. 

Kind Regards !

**Comment by horsiezoo** [comment]
Hi again nevermind, figured it out - yup SD wiring, luckily no magic smoke this time ! Keep up the great work ! 

Regards!

**Comment by evansm7** [comment]
Ha wicked! Glad to hear it can be recreated 😁 have fun. 
(For any others wondering, any disc image file that works with umac will work, copied to SD and named umac0.img)
