### ISSUE TITLE
VGA Connection 

### ISSUE THREAD

**Issue by Martius108** [evansm7/pico-mac#18]
Hello,

I want to solder half of a VGA cable to the Pico and I found this website for the VGA connector pins:

[VGA Connector Pins](https://pc-anwender.de/Blog/Blog-2010/04-07-vga-anschluss-pinbelegung.htm)

It is in german but I hope it is understandable (Masse in german means Ground). In my case I have pins 1-3 for RGB, 4 and 5 not connected, 6-8 GND (soldered together in the connector I assume), 9 not connected but should be for 5V according to the above website, 10 ground for vertical synchronisation, 11 not connected, 12 for SDA, 13 for HSYNC, 14 for VSYNC, 15 for SCL. Is this correct? 

Is there no 5V connection between the Pico and the VGA device? VGA 5 should be the ground for the horizontal synchronisation but it is not connected to a wire in my case. I have only eight coloured wires plus one non-isolated ground wire.

If I understood your description right, I should just connect GND to VGA 6 (7 or 8), HSYNC with 68 ohms (I don’t have 66, but should be ok - or it is better to take a lower value? - I have 47 ohms) to VGA 13, VSYNC with 68 ohms to VGA 14 and Video Out to VGA 1-3 (connect all of them together). I also assume that I have to connect VGA 5 and VGA 10 with ground too, right?

Thanks 
Martin

**Comment by evansm7** [comment]
Hello!
Just connect as many grounds as you have available (as many of 5-8,10 as are wired) all together to the nearest Pico Gnd. Maybe they’ve cheaped out and made the shield connect to all the ground pins? Anyway likely not critical as long as “some” are connected. :)
Then RGB 1-3 together, HS 13, VS 14, to the corresponding resistors. And then, don’t worry about any of the other pins (no I2C, no 5V). Your resistor values sound just fine, 68 will do. (If it doesn’t, try lower, but am pretty sure it’ll be fine.)
Viel Glück!

**Comment by Martius108** [comment]
Works great! Thank you.

**Comment by summerlotus513** [comment]
Hello, I also encountered a similar VGA problem
I set up and tested it at the beginning, I can work normally
Then I found the Universal Board to welded the components. I confirmed that my VGA 1-3 link was connected to the PICO 18 pins of PICO with 100Ω.
VGA 13 pin connect a 66Ω resistor (I get an approximate resistance value through two resistors) connected to the 21 pin of Pico
VGA 14 pin connect 66Ω resistance to the 19 pin of Pico
VGA's 5,6,7,8,10 pin I connect to the GND of Pico (the pin between 19 and 21)
Then he was strange that he didn't work!

**Comment by summerlotus513** [comment]
> Hello, I also encountered a similar VGA problem I set up and tested it at the beginning, I can work normally Then I found the Universal Board to welded the components. I confirmed that my VGA 1-3 link was connected to the PICO 18 pins of PICO with 100Ω. VGA 13 pin connect a 66Ω resistor (I get an approximate resistance value through two resistors) connected to the 21 pin of Pico VGA 14 pin connect 66Ω resistance to the 19 pin of Pico VGA's 5,6,7,8,10 pin I connect to the GND of Pico (the pin between 19 and 21) Then he was strange that he didn't work!

By the way, my display has been in the reciprocating signal and then lost signal.

**Comment by Martius108** [comment]
Please be aware that GOIO 19 is not pin 19. See pinout of the Pico.
